version: '3.7'

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This will use the Build Argument from the Coolify UI
        CONF_TYPE: ${CONF_TYPE:-default} 
    environment:
      # We now use the Kasm container name as the host
      - PROXY_HOST=https://kasm_proxy:8443
    networks:
      # Connect the service to the Kasm network
      - kasm_default_network 
    # The extra_hosts entry is no longer needed
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

# Declare that the Kasm network is an existing, external network
networks:
  kasm_default_network:
    external: true
